name: background_fetch
description: Periodic callbacks in the background for both iOS and Android.  Includes Android Headless implementation.
version: 1.3.5
homepage: https://github.com/XpertLabBd/background_fetch


environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.transistorsoft.flutter.backgroundfetch
        pluginClass: BackgroundFetchPlugin
      ios:
        pluginClass: BackgroundFetchPlugin

